# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cortexkernel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cortexkernel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ortexkernel.proto\x12\x0c\x63ortexkernel\"5\n\x0bNodeRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"B\n\tNodeReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"Z\n\x0b\x45\x64geRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x11\n\tpredicate\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x01(\t\x12\x12\n\nedge_class\x18\x05 \x01(\t\"X\n\tEdgeReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x11\n\tpredicate\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x01(\t\x12\x12\n\nedge_class\x18\x05 \x01(\t\"\x1c\n\x0eGetNodeRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd5\x01\n\x13\x43ortexKernelStorage\x12=\n\x07\x41\x64\x64Node\x12\x19.cortexkernel.NodeRequest\x1a\x17.cortexkernel.NodeReply\x12=\n\x07\x41\x64\x64\x45\x64ge\x12\x19.cortexkernel.EdgeRequest\x1a\x17.cortexkernel.EdgeReply\x12@\n\x07GetNode\x12\x1c.cortexkernel.GetNodeRequest\x1a\x17.cortexkernel.NodeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cortexkernel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEREQUEST']._serialized_start=36
  _globals['_NODEREQUEST']._serialized_end=89
  _globals['_NODEREPLY']._serialized_start=91
  _globals['_NODEREPLY']._serialized_end=157
  _globals['_EDGEREQUEST']._serialized_start=159
  _globals['_EDGEREQUEST']._serialized_end=249
  _globals['_EDGEREPLY']._serialized_start=251
  _globals['_EDGEREPLY']._serialized_end=339
  _globals['_GETNODEREQUEST']._serialized_start=341
  _globals['_GETNODEREQUEST']._serialized_end=369
  _globals['_CORTEXKERNELSTORAGE']._serialized_start=372
  _globals['_CORTEXKERNELSTORAGE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
