# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cortexkernel_pb2 as cortexkernel__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortexkernel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CortexKernelStorageStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddNode = channel.unary_unary(
                '/cortexkernel.CortexKernelStorage/AddNode',
                request_serializer=cortexkernel__pb2.NodeRequest.SerializeToString,
                response_deserializer=cortexkernel__pb2.NodeReply.FromString,
                _registered_method=True)
        self.AddEdge = channel.unary_unary(
                '/cortexkernel.CortexKernelStorage/AddEdge',
                request_serializer=cortexkernel__pb2.EdgeRequest.SerializeToString,
                response_deserializer=cortexkernel__pb2.EdgeReply.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/cortexkernel.CortexKernelStorage/GetNode',
                request_serializer=cortexkernel__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=cortexkernel__pb2.NodeReply.FromString,
                _registered_method=True)


class CortexKernelStorageServicer:
    """Missing associated documentation comment in .proto file."""

    def AddNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexKernelStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=cortexkernel__pb2.NodeRequest.FromString,
                    response_serializer=cortexkernel__pb2.NodeReply.SerializeToString,
            ),
            'AddEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdge,
                    request_deserializer=cortexkernel__pb2.EdgeRequest.FromString,
                    response_serializer=cortexkernel__pb2.EdgeReply.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=cortexkernel__pb2.GetNodeRequest.FromString,
                    response_serializer=cortexkernel__pb2.NodeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortexkernel.CortexKernelStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortexkernel.CortexKernelStorage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexKernelStorage:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexkernel.CortexKernelStorage/AddNode',
            cortexkernel__pb2.NodeRequest.SerializeToString,
            cortexkernel__pb2.NodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexkernel.CortexKernelStorage/AddEdge',
            cortexkernel__pb2.EdgeRequest.SerializeToString,
            cortexkernel__pb2.EdgeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexkernel.CortexKernelStorage/GetNode',
            cortexkernel__pb2.GetNodeRequest.SerializeToString,
            cortexkernel__pb2.NodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
